/* ========================================
   CENTRALIZED STYLES INDEX
   ======================================== */

// ========================================
// CENTRALIZED STYLES INDEX
// ========================================
// Note: CSS files are imported in globals.css to ensure proper Tailwind processing

// Export style objects for component usage
export const navigationStyles = {
  container: 'nav-container',
  content: 'nav-content',
  header: 'nav-header',
  brand: 'nav-brand',
  brandLink: 'nav-brand-link',
  brandIcon: 'nav-brand-icon',
  brandText: 'nav-brand-text',
  menu: 'nav-menu',
  menuButton: 'nav-menu-button',
  menuIcon: 'nav-menu-icon',
  link: 'nav-link',
  linkActive: 'nav-link-active',
  linkInactive: 'nav-link-inactive',
  linkIcon: 'nav-link-icon',
  linkText: 'nav-link-text',
  auth: 'nav-auth',
  authButton: 'nav-auth-button',
  authText: 'nav-auth-text',
  authTextMobile: 'nav-auth-text-mobile',
  userDropdown: 'nav-user-dropdown',
  userButton: 'nav-user-button',
  userAvatar: 'nav-user-avatar',
  userAvatarImage: 'nav-user-avatar-image',
  userChevron: 'nav-user-chevron',
  userChevronOpen: 'nav-user-chevron-open',
  dropdownMenu: 'nav-dropdown-menu',
  dropdownItem: 'nav-dropdown-item',
  dropdownItemIcon: 'nav-dropdown-item-icon',
  dropdownItemButton: 'nav-dropdown-item-button',
  loadingSkeleton: 'nav-loading-skeleton',
  loadingAvatar: 'nav-loading-avatar',
  loadingButton: 'nav-loading-button',
  loadingText: 'nav-loading-text',
  loadingTextMobile: 'nav-loading-text-mobile',
  responsiveContainer: 'nav-responsive-container',
  responsiveMenu: 'nav-responsive-menu',
  responsiveText: 'nav-responsive-text',
  responsiveTextMobile: 'nav-responsive-text-mobile',
};

export const passportStyles = {
  container: 'passport-container',
  header: 'passport-header',
  logo: 'passport-logo',
  logoText: 'passport-logo-text',
  title: 'passport-title',
  subtitle: 'passport-subtitle',
  profile: 'passport-profile',
  profileContent: 'passport-profile-content',
  avatarContainer: 'passport-avatar-container',
  avatar: 'passport-avatar',
  avatarImage: 'passport-avatar-image',
  verificationBadge: 'passport-verification-badge',
  verificationIcon: 'passport-verification-icon',
  profileInfo: 'passport-profile-info',
  profileName: 'passport-profile-name',
  profileRating: 'passport-profile-rating',
  ratingStar: 'passport-rating-star',
  ratingValue: 'passport-rating-value',
  ratingSeparator: 'passport-rating-separator',
  reviewCount: 'passport-review-count',
  stats: 'passport-stats',
  statItem: 'passport-stat-item',
  statValue: 'passport-stat-value',
  statLabel: 'passport-stat-label',
  section: 'passport-section',
  sectionTitle: 'passport-section-title',
  sectionContent: 'passport-section-content',
  sectionSimple: 'passport-section-simple',
  sectionText: 'passport-section-text',
  languages: 'passport-languages',
  languageTag: 'passport-language-tag',
  infoSection: 'passport-info-section',
  infoContent: 'passport-info-content',
  infoItem: 'passport-info-item',
  infoText: 'passport-info-text',
  footer: 'passport-footer',
  verifiedText: 'passport-verified-text',
  trustText: 'passport-trust-text',
  responsiveContainer: 'passport-responsive-container',
  responsiveAvatar: 'passport-responsive-avatar',
  responsiveText: 'passport-responsive-text',
};

export const headerDropdownStyles = {
  userDropdown: {
    container: 'user-dropdown-container',
    button: 'user-dropdown-button',
    avatar: 'user-dropdown-avatar',
    avatarImage: 'user-dropdown-avatar-image',
    chevron: 'user-dropdown-chevron',
    chevronOpen: 'user-dropdown-chevron-open',
    menu: 'user-dropdown-menu',
    email: 'user-dropdown-email',
    list: 'user-dropdown-list',
    item: 'user-dropdown-item',
    itemIcon: 'user-dropdown-item-icon',
    logoutButton: 'user-dropdown-logout-button',
    logoutIcon: 'user-dropdown-logout-icon',
  },
  notificationDropdown: {
    container: 'notification-dropdown-container',
    button: 'notification-dropdown-button',
    indicator: 'notification-dropdown-indicator',
    indicatorHidden: 'notification-dropdown-indicator-hidden',
    indicatorVisible: 'notification-dropdown-indicator-visible',
    ping: 'notification-dropdown-ping',
    icon: 'notification-dropdown-icon',
    menu: 'notification-dropdown-menu',
    header: 'notification-dropdown-header',
    title: 'notification-dropdown-title',
    closeButton: 'notification-dropdown-close-button',
    closeIcon: 'notification-dropdown-close-icon',
    list: 'notification-dropdown-list',
    item: 'notification-dropdown-item',
    avatarContainer: 'notification-dropdown-avatar-container',
    avatar: 'notification-dropdown-avatar',
    avatarImage: 'notification-dropdown-avatar-image',
    statusBadge: 'notification-dropdown-status-badge',
    content: 'notification-dropdown-content',
    meta: 'notification-dropdown-meta',
    dot: 'notification-dropdown-dot',
  },
  dropdownItem: {
    base: 'dropdown-item-base',
    icon: 'dropdown-item-icon',
    text: 'dropdown-item-text',
  },
  responsive: {
    container: 'dropdown-responsive-container',
    menu: 'dropdown-responsive-menu',
    item: 'dropdown-responsive-item',
  },
};

export const formStyles = {
  container: 'form-container',
  wrapper: 'form-wrapper',
  section: 'form-section',
  sectionSpacing: 'form-section-spacing',
  contentSpacing: 'form-content-spacing',
  title: 'form-title',
  subtitle: 'form-subtitle',
  heading: 'form-heading',
  description: 'form-description',
  textCenter: 'form-text-center',
  field: {
    container: 'form-field-container',
    label: 'form-field-label',
    labelRequired: 'form-field-label-required',
    input: 'form-field-input',
    inputWithIcon: 'form-field-input-with-icon',
    icon: 'form-field-icon',
    textarea: 'form-field-textarea',
    select: 'form-field-select',
    checkbox: 'form-field-checkbox',
    checkboxLabel: 'form-field-checkbox-label',
    radio: 'form-field-radio',
    radioLabel: 'form-field-radio-label',
  },
  button: {
    primary: 'form-button',
    secondary: 'form-button-secondary',
  },
  validation: {
    error: 'form-error',
    help: 'form-help',
    success: 'form-success',
    errorMessage: 'form-error-message',
  },
  layout: {
    row: 'form-row',
    group: 'form-group',
    actions: 'form-actions',
    actionsLeft: 'form-actions-left',
    actionsRight: 'form-actions-right',
  },
  links: {
    back: 'form-back-link',
    primary: 'form-link',
    secondary: 'form-link-secondary',
  },
  features: {
    item: 'form-feature-item',
    dot: 'form-feature-dot',
    text: 'form-feature-text',
  },
  responsive: {
    container: 'form-responsive',
    mobile: 'form-mobile-optimized',
  },
  states: {
    loading: 'form-loading',
    loadingText: 'form-loading-text',
  },
  focus: {
    ring: 'form-focus-ring',
  },
  effects: {
    hover: 'form-hover',
  },
  animations: {
    fadeIn: 'form-fade-in',
    slideUp: 'form-slide-up',
  },
};

export const footerStyles = {
  container: 'footer-container',
  mainContent: 'footer-main-content',
  grid: 'footer-grid',
  companyInfo: 'footer-company-info',
  companyHeader: 'footer-company-header',
  companyIcon: 'footer-company-icon',
  companyName: 'footer-company-name',
  companyDescription: 'footer-company-description',
  socialLinks: 'footer-social-links',
  socialLink: 'footer-social-link',
  socialSrOnly: 'footer-social-sr-only',
  section: 'footer-section',
  sectionLinks: 'footer-section-links',
  sectionLink: 'footer-section-link',
  contactSection: 'footer-contact-section',
  contactGrid: 'footer-contact-grid',
  contactItem: 'footer-contact-item',
  contactIcon: 'footer-contact-icon',
  contactLink: 'footer-contact-link',
  bottomBar: 'footer-bottom-bar',
  bottomContent: 'footer-bottom-content',
  bottomFlex: 'footer-bottom-flex',
  copyright: 'footer-copyright',
  bottomLinks: 'footer-bottom-links',
  bottomLink: 'footer-bottom-link',
};

// Export all styles as a single object
export const allStyles = {
  navigation: navigationStyles,
  passport: passportStyles,
  headerDropdowns: headerDropdownStyles,
  form: formStyles,
  footer: footerStyles,
};

// Default export
export default allStyles;
