export enum RealEstateOfferAction {
    INITIATOR_CREATED = 'INITIATOR_CREATED',
    INITIATOR_EDITED = 'INITIATOR_EDITED',
    INITIATOR_CANCELLED = 'INITIATOR_CANCELLED',
    INITIATOR_ACCEPTED = 'INITIATOR_ACCEPTED',
    INITIATOR_COUNTERED = 'INITIATOR_COUNTERED',
    INITIATOR_REJECTED = 'INITIATOR_REJECTED',
    RECIPIENT_CREATED = 'RECIPIENT_CREATED',
    RECIPIENT_EDITED = 'RECIPIENT_EDITED',
    RECIPIENT_CANCELLED = 'RECIPIENT_CANCELLED',
    RECIPIENT_ACCEPTED = 'RECIPIENT_ACCEPTED',
    RECIPIENT_COUNTERED = 'RECIPIENT_COUNTERED',
    RECIPIENT_REJECTED = 'RECIPIENT_REJECTED'
}
  